name: Build and Deploy
on: [push]
permissions:
  contents: write

# 任务
jobs:
  build-and-deploy:
    # 服务器环境：最新版 Ubuntu
    runs-on: ubuntu-latest
    steps:
      # 拉取代码
      - name: Checkout
        uses: actions/checkout@v3

      # 生成静态文件
      - name: Build
        run: export NODE_OPTIONS=--openssl-legacy-provider && npm install && npm run build

      # 部署到 GitHub Pages
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: site